version: "3.8"

services:

  app:
    build:
      context: .
    networks:
      - simple-redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8090:8090

networks:
  simple-redis: